-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jan 10, 2024 at 02:18 PM
-- Server version: 10.6.16-MariaDB
-- PHP Version: 8.1.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zeleamas_boilerinstallationuk`
--

-- --------------------------------------------------------

--
-- Table structure for table `boilers`
--

CREATE TABLE `boilers` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `meta_description` text DEFAULT NULL,
  `meta_keywords` text DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `main_description` text NOT NULL,
  `secondary_description` text NOT NULL,
  `spec_1` text NOT NULL,
  `spec_2` text NOT NULL,
  `spec_3` text NOT NULL,
  `spec_4` text NOT NULL,
  `spec_5` text NOT NULL,
  `brand` text NOT NULL,
  `dimensions` text NOT NULL,
  `flow_rate` text NOT NULL,
  `ErP_rating_heating` text NOT NULL,
  `ErP_rating_DHW` text NOT NULL,
  `ErP_efficiency` text NOT NULL,
  `image_1` varchar(255) DEFAULT NULL,
  `image_2` varchar(255) DEFAULT NULL,
  `image_3` varchar(255) DEFAULT NULL,
  `image_4` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `boilers`
--

INSERT INTO `boilers` (`id`, `name`, `slug`, `meta_description`, `meta_keywords`, `price`, `main_description`, `secondary_description`, `spec_1`, `spec_2`, `spec_3`, `spec_4`, `spec_5`, `brand`, `dimensions`, `flow_rate`, `ErP_rating_heating`, `ErP_rating_DHW`, `ErP_efficiency`, `image_1`, `image_2`, `image_3`, `image_4`, `created_at`, `updated_at`) VALUES
(8, 'Vaillant ecoTEC Plus 825 25kW', 'vaillant-ecotec-plus-825-25kw', 'Upgrade your home heating with Vaillant ecoTEC Plus 825 25kW boiler! Enjoy energy efficiency and reliable performance. Find the perfect balance of comfort and eco-friendliness for your home. Explore advanced technology and superior heating solutions today!', 'Vaillant ecoTEC Plus 825, 25kW boiler, Energy-efficient heating, Reliable hot water, Eco-friendly technology, Compact design, Home heating solution, Advanced heating system, Sustainable living, Energy savings', 1999.00, 'The Vaillant ecoTEC Plus 825 25kW boiler offers cutting-edge heating technology, ensuring optimal warmth and efficiency for your home. With its compact design and powerful performance, this boiler provides reliable hot water and heating while minimizing energy consumption. Experience superior comfort and reduced utility bills with Vaillant\'s advanced ecoTEC Plus 825 25kW, the perfect choice for modern, eco-conscious households.', 'Upgrade to Vaillant ecoTEC Plus 825 25kW for efficient, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, blending advanced technology with energy savings. Experience comfort and sustainability today!', 'Instant hot water delivery in just 5 seconds', 'Flame lift detection system', 'Stylish contoured case design with down flap', 'Wide modulation range of up to 1:6', 'Built-in-two-stage frost protection', 'Vaillant', '440 x 720 x 338', '10.5', 'A', 'A', '89.4%', 'images/boilers/XfJo269xI9T6sT1IFlJiQ1t8sR5B6m-metaVmFpbGxhbnQtZWNvVEVDLVBsdXMtODI1LTI1a1ctZnJvbnQud2VicA==-.webp', 'images/boilers/WgzxXS3yWjrc9AOLLOoz5IGRUSueqD-metaVmFpbGxhbnQtZWNvVEVDLVBsdXMtODI1LTI1a1ctZnJvbnQtNC53ZWJw-.webp', 'images/boilers/CGKy8yD0xMduPoCLcRN13uGwfjyXcF-metaVmFpbGxhbnQtZWNvVEVDLVBsdXMtODI1LTI1a1ctZnJvbnQtMi53ZWJw-.webp', 'images/boilers/MhKIakt6ea4g0s3480hrXK2AS3bDYs-metaVmFpbGxhbnQtZWNvVEVDLVBsdXMtODI1LTI1a1ctZnJvbnQtMy53ZWJw-.webp', '2023-10-07 07:39:54', '2023-10-07 07:39:54'),
(9, 'Baxi 825 Combi Boiler 25kW', 'baxi-825-combi-boiler-25kw', 'Upgrade your home heating with the Baxi 825 Combi Boiler 25kW! Experience unparalleled warmth and energy efficiency. Enjoy reliable hot water and cutting-edge heating technology. Discover eco-friendly solutions and modern comfort tailored for your home today!', 'Baxi 825 Combi Boiler, 25kW heating, Instant hot water, Advanced heating technology, Compact design, Eco-conscious home, Energy savings, Reliable hot water supply, Sustainable living, High-efficiency heating.', 1799.00, 'Discover the Baxi 825 Combi Boiler 25kW, where innovation meets comfort. Engineered for optimal warmth and efficiency, this boiler ensures reliable hot water and heating while minimizing energy consumption. Embrace unmatched comfort and reduced utility bills with Baxi\'s advanced 825 Combi Boiler, designed for eco-conscious households.', 'Elevate your home\'s heating with the Baxi 825 Combi Boiler 25kW. This powerhouse delivers instant hot water and consistent warmth, blending advanced technology with energy savings. Experience exceptional comfort and sustainability tailored to your lifestyle today!', 'Stainless Steel Heat Exchanger', 'Top Flue Outlet', 'LCD Display', 'OpenTherm Interface', 'British-built, compact and lightweight', 'Baxi', '450 x 780 x 345', '10.2', 'A', 'A', '93', 'images/boilers/zgV66xoKRznCU82huLNWJJeqSD9Rl4-metaQmF4aS04MjUtQ29tYmktQm9pbGVyLTI1a1cud2VicA==-.webp', NULL, NULL, NULL, '2023-10-07 07:54:38', '2023-10-07 07:54:38'),
(10, 'Potterton Promax 24 kW ErP', 'potterton-promax-24-kw-erp', 'Elevate your home heating experience with the Potterton Promax 24 kW ErP boiler! Discover unmatched efficiency and reliable performance. Achieve the perfect blend of comfort and environmental responsibility for your household. Explore innovative technology and exceptional heating solutions now!', 'Potterton Promax 24 kW ErP, Energy-efficient heating, Reliable hot water supply, Eco-conscious technology, Space-saving design, Home heating solution, Advanced heating system, Sustainable living, Energy savings, Efficient boiler installation.', 1299.00, 'Introducing the Potterton Promax 24 kW ErP boiler, a pinnacle of cutting-edge heating technology designed to provide unparalleled warmth and efficiency for your home. With its space-saving design and robust performance, this boiler ensures consistent hot water supply and heating while minimizing energy consumption. Embrace superior comfort and reduced utility costs with Potterton\'s advanced Promax 24 kW ErP, the ultimate choice for modern, eco-conscious households.', 'Upgrade your home to the Potterton Promax 24 kW ErP for efficient, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, seamlessly integrating advanced technology with energy savings. Experience unmatched comfort and sustainability today!', 'Compatible with the Multifit GasSaver', 'Compatible with Potterton Solar, Megaflo Eco Solar Cylinder and Santon Premier Plus Solar Cylinder', 'Pre-plumbing jig included so that pipe work can be pre-installed', 'Flueing options up to 20m allowing greater flexibility of siting', 'Optional stand off bracket which allows pipes to be routed behind the boiler', 'Potterton', '400 x 980 x 500 ', '10.5', 'A', 'A', '93.9%', 'images/boilers/zkfUl5qSDirtouBp9uM88nVN90ymRe-metaUG90dGVydG9uLVByb21heC0yNC1rVy1FclAud2VicA==-.webp', NULL, NULL, NULL, '2023-10-07 08:11:19', '2023-10-07 08:11:19'),
(11, 'Worcester Greenstar 4000 30kW', 'worcester-greenstar-4000-30kw', 'Elevate your home\'s warmth with the Worcester Greenstar 4000 30kW boiler! Experience unmatched energy efficiency and dependable performance. Discover a harmonious blend of luxury and eco-consciousness for your residence. Dive into cutting-edge technology and superior heating solutions today!', 'Worcester Greenstar 4000 30kW, 30kW boiler, High-efficiency heating, Reliable hot water supply, Eco-friendly design, Space-saving solution, Advanced heating technology, Sustainable living, Energy savings, Boiler installation experts.', 1899.00, 'The Worcester Greenstar 4000 30kW boiler stands at the forefront of innovative heating solutions, promising optimal warmth and efficiency for your home. Its sleek design and robust performance ensure a constant supply of hot water and heating while minimizing energy usage. Experience unparalleled comfort and lowered utility costs with Worcester\'s state-of-the-art Greenstar 4000 30kW – the ultimate choice for contemporary, environmentally-conscious households.', 'Upgrade your home to the Worcester Greenstar 4000 30kW for seamless, eco-friendly heating. This powerful, space-saving unit delivers reliable hot water and warmth, seamlessly integrating advanced technology with energy efficiency. Revel in comfort and sustainability like never before!', 'Wide power range helps to reduce gas consumption and lower energy bills', 'Innovative \'Quick Tap\' water saving function helps you reduce water waste', 'The modern new design comes with an easy to use colour display', 'One of the quietest combi boilers available, making it easy to live with', 'Features wireless connectivity with the Bosch EasyControl', 'Worcester', '724 x 400 x 310', '10.8', 'A', 'A', '94.5%', 'images/boilers/eeFb4lSUxyhIAH47uMCNPRCB862vDP-metad29yY2VzdGVyLWdyZWVuc3Rhci00MDAwLTMwa3cud2VicA==-.webp', 'images/boilers/kNlXC6HHQIpUMNyuyThUe38XBNATI5-metad29yY2VzdGVyLWdyZWVuc3Rhci00MDAwLTMwa3ctMi53ZWJw-.webp', NULL, NULL, '2023-10-07 08:19:19', '2023-10-07 08:19:19'),
(12, 'Baxi 830 30kW 800', 'baxi-830-30kw-800', 'Transform your home heating with the Baxi 830 30kW 800 boiler! Experience unparalleled energy efficiency and unwavering performance. Discover a harmonious blend of luxury and eco-consciousness for your residence. Dive into advanced technology and superior heating solutions today!', 'Baxi 830 30kW 800, 30kW boiler, High-efficiency heating, Reliable hot water supply, Eco-friendly design, Compact solution, Advanced heating technology, Sustainable living, Energy savings, Expert boiler installation.', 1899.00, 'The Baxi 830 30kW 800 boiler represents the pinnacle of innovative heating solutions, ensuring optimal warmth and efficiency for your home. Its compact design and powerful performance guarantee a consistent supply of hot water and heating while minimizing energy usage. Experience unmatched comfort and lowered utility costs with Baxi\'s state-of-the-art 830 30kW 800 – the ultimate choice for contemporary, environmentally-conscious households.', 'Upgrade your home to the Baxi 830 30kW 800 for seamless, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, seamlessly integrating advanced technology with energy efficiency. Revel in comfort and sustainability like never before!', 'Small in size and lightweight, for quick, easy installation', 'A magnetic filter, to keep your pipework clean and fully functioning', 'Optional smart controls', '20% Hydrogen blend ready', 'An efficiency rating of 93%', 'Baxi', '390 x 700 x 285', '12.2 l/min', 'A', 'A', '93%', 'images/boilers/E8jBp76CdwkpYDfmvEgyNC3ZZGlwJi-metaYmF4aS04MzAtMzBrdy04MDAud2VicA==-.webp', 'images/boilers/SG9cCvbnXOpoOR0t6f85rLKUFhomzE-metaYmF4aS04MzAtMzBrdy04MDAtYmFjay53ZWJw-.webp', 'images/boilers/IV88Czzxs8Si0ivth3W0LyRDdbq7xc-metaYmF4aS04MzAtMzBrdy04MDAtZnJvbnQud2VicA==-.webp', NULL, '2023-10-07 08:30:22', '2023-10-07 08:30:22'),
(13, 'Vaillant ecoFIT Pure 825 25kW', 'vaillant-ecofit-pure-825-25kw', 'Elevate your home\'s heating with the Vaillant ecoFIT Pure 825 25kW boiler! Experience top-tier energy efficiency and consistent performance. Strike the perfect balance between luxury and eco-consciousness for your residence. Immerse yourself in advanced technology and superior heating solutions today!', 'Vaillant ecoFIT Pure 825 25kW, 25kW combi boiler, High-efficiency heating, Reliable hot water supply, Eco-friendly design, Compact solution, Advanced heating technology, Sustainable living, Energy savings, Expert boiler installation.', 1899.00, 'The Vaillant ecoFIT Pure 825 25kW boiler stands as the epitome of innovative heating solutions, ensuring optimal warmth and efficiency for your home. Its compact size and optional rear flue fitting make it ideal for snug installations, including kitchen cupboards and small cloakroom spaces. The powerful aluminum heat exchanger offers outstanding performance and low energy consumption. When less heat is needed, it reduces itself to just 20% of its maximum output, ensuring greater energy efficiency and lower bills. This boiler is also compatible with vSMART technology, allowing you to control heating and hot water remotely. Packaged with a horizontal flue pipe for added convenience and value, the ecoFIT Pure 825 guarantees ease of installation and maintenance.', 'Upgrade your home to the Vaillant ecoFIT Pure 825 25kW for seamless, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, blending advanced technology with energy efficiency. Revel in comfort and sustainability like never before!', 'Designed for easy installation and maintenance, making it a hassle-free choice for homeowners.', 'Boasts an impressive SEDBUK SAP 2009 Rating of 89.60% and SEDBUK SAP 2005 Rating of 90.60%, ensuring excellent energy efficiency.', 'Allows remote control of heating and hot water, enhancing convenience and energy savings.', ' Heat Output: 25 kW, DHW Output: 25.2 kW, DHW Flow Rate at 35 Degree Rise: 10.4 L/min, CH Condensing Max Output: 18.3 kW, ensuring reliable and consistent heating and hot water supply.', 'Comes with a packaged horizontal flue, providing additional convenience and value.', 'Vaillant', '390 x 700 x 295', '10.4 l/min', 'A', 'A', '90.60%', 'images/boilers/gbrqrLxlmnfajiHKGE6kmtCwunCv17-metadmFpbGxhbnQtZWNvZml0LXB1cmUtODI1LTI1a3cud2VicA==-.webp', 'images/boilers/4pEembKZSyzzsVJjE9sMsRabUz1RMr-metadmFpbGxhbnQtZWNvZml0LXB1cmUtODI1LTI1a3ctMi53ZWJw-.webp', 'images/boilers/hgsviHOwChnC7Yakfb8FKltw0xj7MS-metadmFpbGxhbnQtZWNvZml0LXB1cmUtODI1LTI1a3ctY2xvc2UtbG9vay53ZWJw-.webp', 'images/boilers/ZPv7KwCODkicGycHdBqfoI6ChxiXrJ-metadmFpbGxhbnQtZWNvZml0LXB1cmUtODI1LTI1a3ctc21hcnQtY29udHJvbC53ZWJw-.webp', '2023-10-07 08:39:49', '2023-10-07 08:39:49'),
(14, 'Baxi 24kW 600 Combi', 'baxi-24kw-600-combi', 'Enhance your home\'s warmth with the Baxi 24kW 600 Combi boiler! Experience exceptional energy efficiency and unwavering performance. Strike the perfect balance between luxury and eco-consciousness for your residence. Immerse yourself in advanced technology and superior heating solutions today!', 'Baxi 24kW 600 Combi, 24kW gas combi boiler, High-efficiency heating, Reliable hot water supply, Compact design, Advanced heating technology, Energy savings, Baxi boiler installation experts.', 1499.00, 'The Baxi 24kW 600 Combi boiler is engineered to fit into a compact 290 mm deep cupboard, weighing a mere 29.5 kg, providing a powerful heating solution in a super compact size. It features an easy-fill permanent filling loop, brass hydraulics, a simple hanging bracket, and an Opentherm interface. Operate it with ease using smart controls through an app on your phone or tablet. This boiler not only delivers high efficiency but also offers convenience with its built-in drip tray and extensive flue options up to 20 m. Endorsed by the Energy Saving Trust and backed by a 7-year warranty upon registration, the Baxi 24kW 600 Combi ensures reliable performance and peace of mind.', 'Upgrade your home to the Baxi 24kW 600 Combi for seamless, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, blending advanced technology with energy efficiency. Revel in comfort and sustainability like never before!', 'Fits into a 290 mm deep cupboard, making it ideal for tight spaces.', 'Features a simple hanging bracket and an easy-fill permanent filling loop for hassle-free installation and maintenance.', 'Operate the boiler through smart controls via an app on your phone or tablet, ensuring convenience and energy savings.', 'Allows seamless integration with compatible smart home systems.', 'Heat Output: 24 kW, DHW Output: 25.77 kW, DHW Flow Rate at 35 Degree Rise: 10.2 l/min, CH Condensing Max Output: 21.6 kW, ensuring reliable and consistent heating and hot water supply.', 'Baxi', '394 x 704 x 289 ', '10.2 l/min', 'A', 'A', '94.9%', 'images/boilers/d4uwQXnUTQeLfSJJ8bR1AnZdb4Eylv-metaYmF4aS0yNGt3LTYwMC1jb21iaS5qcGVn-.jpg', NULL, NULL, NULL, '2023-10-07 08:47:15', '2023-10-07 08:47:15'),
(15, 'Baxi 424 Combi 2 24kW', 'baxi-424-combi-2-24kw', 'Elevate your home heating with the Baxi 424 Combi 2 24kW boiler! Experience unparalleled energy efficiency and consistent performance. Discover the perfect blend of luxury and eco-consciousness for your residence. Immerse yourself in advanced technology and superior heating solutions today!', 'Baxi 424 Combi 2 24kW, 24kW gas combi boiler, High-efficiency heating, Reliable hot water supply, Compact design, Advanced heating technology, Energy savings, Baxi boiler installation experts.', 1499.00, 'The Baxi 424 Combi 2 24kW boiler sets new standards in high-efficiency heating. Engineered for compact cupboard fit, this boiler delivers optimal warmth and reliability. Its top central flue position and easy wiring save installation time, ensuring convenience for both engineers and homeowners. OpenTherm control compatibility maximizes efficiency, and the boiler is upgradeable to a consumer-connected service, enhancing user experience. With a robust brass hydraulic block, integral pressure gauge for engineers, and a 5-year parts and labor warranty, this boiler provides unparalleled peace of mind.', 'Upgrade your home to the Baxi 424 Combi 2 24kW for seamless, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, blending advanced technology with energy efficiency. Revel in comfort and sustainability like never before!', 'Designed to fit snugly into cupboards, optimizing space utilization.', 'Offers versatile flue installation options, ensuring flexibility in placement.', 'Simplified wiring saves time during installation, enhancing efficiency.', 'Maximizes energy efficiency by enabling smart control systems.', 'Low noise level of 48 dB ensures a peaceful home environment.', 'Baxi', '1000 x 700 x 1200', '9.8 l/min', 'A', 'A', '93%', 'images/boilers/JHlHBPOsw0j6xmz4IinCZrHhynYdgq-metaYmF4aS00MjQtY29tYmktMi0yNGt3LndlYnA=-.webp', NULL, NULL, NULL, '2023-10-07 09:01:22', '2023-10-07 09:01:22'),
(16, 'Main Eco Compact 25 kW', 'main-eco-compact-25-kw', 'Upgrade your home heating with Main Eco Compact 25 kW boiler! Experience unparalleled energy efficiency and reliable performance. Strike the perfect balance of comfort and eco-friendliness for your residence. Discover advanced technology and superior heating solutions today!', 'Main Eco Compact 25 kW, 25kW gas combi boiler, High-efficiency heating, Reliable hot water supply, Compact cupboard fit, Energy savings, Main boiler installation experts.', 1399.00, 'The Main Eco Compact 25 kW boiler is the result of extensive research and development, tailored to meet the demands of modern households. Designed for cupboard-fit convenience, this lightweight powerhouse delivers optimal warmth and reliability. With its top central flue, brass hydraulics block, and an optional stand-off frame, it optimizes space utilization while providing exceptional heating and hot water performance. Engineered for energy efficiency, this boiler boasts a 93% efficiency rating and an ErP A rating for both heating and hot water. Its 25kW output makes it ideal for medium-sized homes, ensuring consistent comfort while saving on energy bills. Experience eco-conscious heating without compromising on performance.', 'Upgrade to Main Eco Compact 25 kW for efficient, eco-friendly heating. This compact powerhouse delivers reliable hot water and warmth, blending advanced technology with energy efficiency. Experience comfort and sustainability like never before!', 'Designed to fit snugly into cupboards, optimizing space utilization.', ' Offers versatile flue installation options, ensuring flexibility in placement.', 'Fully compatible with the Baxi uSense wired smart thermostat, enabling advanced control and energy savings.', 'Meets the latest regulations for energy efficiency and performance.', 'Rated class 5 (the best) for low emissions, contributing to environmental sustainability.', 'Main', '1000 x 700 x 1200', '12 l/min', 'A', 'A', '93%', 'images/boilers/iKGgOZezmyIkkyBCyaeWnSOXIna9EF-metabWFpbi1lY28tY29tcGFjdC0yNS1rdy53ZWJw-.webp', 'images/boilers/t6J0YhmGSMC3oGBJ4PP1qWtdk378Wt-metabWFpbi1lY28tY29tcGFjdC0yNS1rdy0yLndlYnA=-.webp', NULL, NULL, '2023-10-07 09:07:56', '2023-10-07 09:07:56'),
(17, 'Biasi Rinnova Adaptive 25C 25kW', 'biasi-rinnova-adaptive-25c-25kw', 'Upgrade your home heating with Biasi Rinnova Adaptive 25C 25kW boiler! Enjoy adaptive gas technology and reliable performance. Discover the perfect blend of comfort, efficiency, and eco-friendliness for your residence. Explore advanced features and superior heating solutions today!', 'Biasi Rinnova Adaptive 25C, 25kW gas adaptive boiler, Instantaneous hot water, Gas Adaptive technology, Eco-friendly heating, Compact design, Energy savings, Biasi boiler installation experts.', 1199.00, 'Introducing Rinnova Adaptive, our pioneering gas adaptive boiler now available in the UK market. Compact yet powerful, the Rinnova Adaptive 25C 25kW combination boiler delivers up to 17.0 liters per minute of instantaneous hot water. Equipped with Gas Adaptive technology, it automatically adjusts to different gas qualities, ensuring optimal performance and efficiency. The high-grade stainless steel, single-coil heat exchanger is robust and efficient, providing reliable heating and hot water. With user-friendly controls and optional external control compatibility, Rinnova Adaptive offers ease of operation and enhanced comfort. Featuring built-in weather compensation, it responds to outside temperature changes, optimizing your heating and saving energy. Environmentally conscious, the Rinnova boiler incorporates metal panels and a brass hydraulic block, reducing plastic usage and promoting sustainability. Upgrade to Rinnova Adaptive for adaptive gas technology, eco-friendliness, and superior performance.', 'Upgrade to Biasi Rinnova Adaptive 25C 25kW for efficient, eco-friendly heating. This adaptable powerhouse delivers reliable hot water and warmth, blending advanced Gas Adaptive technology with energy efficiency. Experience unmatched comfort and sustainability today!', 'Adaptive Gas Technology for efficient performance', 'High-grade stainless steel, single-coil heat exchanger for reliability', 'Built-in weather compensation for energy-saving heating', 'User-friendly controls and optional external control compatibility', 'Compact design with metal panels and brass hydraulic block', 'Biasi', '700 x 400 x 300', '10.7 L/min', 'A', 'A', '94%', 'images/boilers/j1Ggk4UFwa0y4VeLCgNk55mfSx4iho-metaYmlhc2ktcmlubm92YS1hZGFwdGl2ZS0yNWMtMjVrdy1mcm9udC53ZWJw-.webp', 'images/boilers/IGFCooopRW4gJtlsTM6BIHz9ZlCrO8-metaYmlhc2ktcmlubm92YS1hZGFwdGl2ZS0yNWMtMjVrdy1pbnNpZGUud2VicA==-.webp', NULL, NULL, '2023-10-07 09:14:47', '2023-10-07 09:14:47'),
(18, 'Glow-worm Compact 24kW', 'glow-worm-compact-24kw', 'Upgrade your home heating with Glow-worm Compact 24kW boiler! Experience reliable performance and energy efficiency in a compact design. Find the perfect blend of comfort and eco-friendliness for your residence. Explore advanced technology and superior heating solutions today!', 'Glow-worm Compact 24kW, Compact Combi Boiler, Small footprint, Energy-efficient heating, Reliable performance, User-friendly installation, Compact design, Eco-friendly technology.', 1299.00, 'Introducing the Glow-worm Compact 24kW, the most compact and lightweight boiler ever produced, delivering powerful performance without sacrificing space. This sturdy and reliable boiler ensures the durability your customers love, providing reliable heating and hot water. Its small footprint allows for flexible and fast installation, fitting into standard 300mm cupboards effortlessly. The user-friendly display enables quick and easy commissioning, saving you time and effort during installation. With a stainless steel heat exchanger, this boiler guarantees long-lasting, efficient performance. Upgrade to Glow-worm Compact 24kW for reliability, efficiency, and hassle-free installation.', 'Upgrade to Glow-worm Compact 24kW for efficient, eco-friendly heating. This small but mighty powerhouse delivers reliable hot water and warmth, combining advanced technology with energy savings. Experience comfort and sustainability in one compact package!', 'Fits snugly into small spaces with dimensions of 626 x 400 x 270 mm', 'Hassle-free setup with a 25mm spacer frame for efficient piping', 'Offers an add-on analogue clock for convenient heating control', 'Durable performance ensured by a corrosion-resistant exchanger', 'Environmentally friendly with low emissions of 27 mg/kWh', 'Glow-worm', '626 x 400 x 270', '9.9 l/min', 'A', 'A', '92%', 'images/boilers/wO4arHSRG5MJYEdE8vNiZkIyJh1wyD-metaZ2xvdy13b3JtLWNvbXBhY3QtMjRrdy1mcm9udC53ZWJw-.webp', 'images/boilers/f3EiloWc8zkXkkRuQIZntCnz4whST9-metaZ2xvdy13b3JtLWNvbXBhY3QtMjRrdy1zY3JlZW4ud2VicA==-.webp', 'images/boilers/iheqaw4RsHJ263pcYzt6Lj9wX4Xjho-metaZ2xvdy13b3JtLWNvbXBhY3QtMjRrdy1zaWRlLndlYnA=-.webp', 'images/boilers/azsfOC65LZA0ooXo1ElNUBU1XHPTe3-metaZ2xvdy13b3JtLWNvbXBhY3QtMjRrdy1ib3R0b20ud2VicA==-.webp', '2023-10-07 09:23:18', '2023-10-07 09:23:18'),
(19, 'Ideal Atlantic 24 25kW', 'ideal-atlantic-24-25kw', 'Elevate your home heating with Ideal Atlantic 24 25kW boiler! Embrace efficiency and warmth in a compact design. Experience cutting-edge technology and exceptional performance. Upgrade your living sustainably today!', 'Ideal Atlantic 24, 25kW boiler, Compact heating, Efficient hot water, Frost protection, Built-in timer, Home heating solution, Advanced technology, Space-saving design, Energy savings.', 1299.00, 'Ideal Atlantic 24 25kW combines high performance with space-saving brilliance. Perfect for snug spaces, this boiler fits seamlessly, ensuring quick installation and robust efficiency. With a built-in timer and frost protection, it\'s the ideal choice for modern homes.', 'Upgrade to Ideal Atlantic 24 25kW for efficient, eco-friendly heating. This powerhouse delivers instant hot water and warmth, blending advanced technology with energy savings. Embrace comfort and sustainability effortlessly!', 'Swift and simple setup, perfect for homes where space is a premium.', 'Fits snugly into standard kitchen cupboards, optimizing space usage.', 'Built-in feature ensures reliable performance even in chilly conditions.', 'A-rated for both hot water and heating, maximizing energy efficiency.', 'Enjoy added convenience with the integrated timer for customized heating schedules.', 'Ideal Atlantic', '395 x 700 x 285', '9.9 l/min', 'A', 'A', '89%', 'images/boilers/8rZ9nzFZFBOq8dDjkhWD4cyDll51JF-metaaWRlYWwtYXRsYW50aWMtMjQtMjVrdy5qcGc=-.jpg', NULL, NULL, NULL, '2023-10-07 09:30:19', '2023-10-07 09:30:19'),
(20, 'Vokera Easi-Heat i 25kW', 'vokera-easi-heat-i-25kw', 'Elevate your home heating with the Vokera Easi-Heat i 25kW combi boiler! Experience compact versatility and future-proof technology. Enjoy instant heating and hot water, all in an eco-friendly design. Upgrade your home heating today!', 'Vokera Easi-Heat i 25kW, Combi boiler, Instant heating, Hot water on demand, Compact design, Energy-efficient technology, Versatile installation, Future-proof heating, Eco-friendly solution.', 1199.00, 'The Vokera Easi-Heat i 25kW combi boiler delivers unparalleled heating performance in a compact form. Its low lift weight allows flexible installation, making it suitable for various spaces, even within kitchen cupboards. With a user-friendly digital interface, large radial stainless steel heat exchanger, and built-in frost protection, it ensures efficiency, ease of use, and reliability.', 'Upgrade to the Vokera Easi-Heat i 25kW for a seamless blend of comfort and efficiency. This combi boiler offers instantaneous heating and hot water, adapting effortlessly to your home\'s needs. Experience advanced technology, versatility, and eco-friendly heating solutions today!', 'Designed for flexible installation, this boiler can fit into various spaces, ensuring heating wherever you need it.', 'Approved for use with hydrogen/methane blend (20/80), making it environmentally friendly and ready for future energy trends.', 'With an ErP Class A rating, it delivers energy efficiency while providing instant hot water and heating.', 'The easy-to-use digital interface ensures effortless control, allowing you to adjust settings according to your preferences.', 'Offers precise control over heating output, ensuring optimal comfort and energy savings.', 'Vokera', '400 x 700 x 275', '10.2 l/min', 'A', 'A', '89.10%', 'images/boilers/kExcskEZLXDeplJMMgLH9CsSvMHo4J-metadm9rZXJhLWVhc2ktaGVhdC1pLTI1a3ctZnJvbnQud2VicA==-.webp', 'images/boilers/suTcbuM3ffhB9ITo4W2p0RDtIVSI3M-metadm9rZXJhLWVhc2ktaGVhdC1pLTI1a3cud2VicA==-.webp', 'images/boilers/9Vnpstaocyr9IKmDg78Xhci2Iq07mc-metadm9rZXJhLWVhc2ktaGVhdC1pLTI1a3ctbGVmdC53ZWJw-.webp', NULL, '2023-10-07 09:37:06', '2023-10-07 09:37:06');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `boilers`
--
ALTER TABLE `boilers`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `boilers_slug_unique` (`slug`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `boilers`
--
ALTER TABLE `boilers`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
